shopware:
  api:
    max_limit: 500
    api_browser:
      auth_required: true
    store:
      context_lifetime: 'P10D' # 1 day interval, see also https://www.php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
      max_limit: 100

  admin_worker:
    enable_admin_worker: false
#    enable_queue_stats_worker: true
#    enable_notification_worker: true
#    # This has to be lower than PHP's max_execution_time (default: 30s)
#    poll_interval: 20
#    transports: ["async", "low_priority"]

#  dal:
#    batch_size: 125
#    max_rule_prices: 100
#    versioning:
#      expire_days: 30
  cart:
    compress: false
    expire_days: 120
    storage:
      # supported types: mysql, redis
      type: "mysql"
        # config:
      # dsn: 'redis://localhost'

  sales_channel_context:
    expire_days: 120

  html_sanitizer:
    enabled: false
#    cache_dir: '%kernel.cache_dir%'
#    cache_enabled: true
#    sets:
#      - name: HTML5
#        tags: ["article", "aside", "audio", "bdi", "canvas", "datalist", "details", "dialog", "embed", "figcaption", "figure", "footer", "header", "main", "mark", "meter", "nav", "progress", "rp", "rt", "ruby", "section", "summary", "time", "wbr", "output", "canvas", "svg", "track", "video", "source", "input"]
#        attributes: ["controls", "open", "min", "max", "datetime", "for", "type", "kind", "srclang", "label", "value", "placeholder", "autoplay", "loop", "muted", "preload", "low", "high", "optimum", "default", "poster", "media", "maxlength", "minlength", "pattern", "required", "autocomplete", "autofocus", "disabled", "readonly", "multiple", "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget", "list", "step", "checked", "accept"]
#      - name: basic
#        tags: ["a", "abbr", "acronym", "address", "b", "bdo", "big", "blockquote", "br", "caption", "center", "cite", "code", "col", "colgroup", "dd", "del", "dfn", "dir", "div", "dl", "dt", "em", "font", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "ins", "kbd", "li", "menu", "ol", "p", "pre", "q", "s", "samp", "small", "span", "strike", "strong", "sub", "sup", "table", "tbody", "td", "tfoot", "th", "thead", "tr", "tt", "u", "ul", "var", "img"]
#        attributes: ["align", "bgcolor", "border", "cellpadding", "cellspacing", "cite", "class", "clear", "color", "colspan", "dir", "face", "frame", "height", "href", "id", "lang", "name", "noshade", "nowrap", "rel", "rev", "rowspan", "scope", "size", "span", "start", "style", "summary", "title", "type", "valign", "value", "width", "target", "src", "alt"]
#        options:
#          - key: Attr.AllowedFrameTargets
#            values: ['_blank', '_self', '_parent', '_top']
#          - key: Attr.AllowedRel
#            values: ['nofollow', 'print']
#          - key: Attr.EnableID
#            value: true
#      - name: media
#        tags: ["img"]
#        attributes: ["src", "alt"]
#      - name: script
#        tags: ["script"]
#        options:
#          - key: HTML.Trusted
#            value: true
#      - name: tidy
#        options:
#          - key: Output.TidyFormat
#            value: true
#      - name: bootstrap
#        tags: ["a", "span"]
#        attributes: ["role", "aria-label", "aria-labelledly", "aria-current", "aria-expanded", "aria-controls", "aria-hidden", "aria-describedby", "tabindex", "aria-modal", "data-bs-toggle", "data-bs-target", "data-bs-dismiss", "data-bs-slide", "data-bs-slide-to", "data-bs-parent", "data-bs-config", "data-bs-content", "data-bs-spy"]
#        custom_attributes:
#          - tags: ["a", "span"]
#            attributes: ["href", "role", "aria-label", "aria-labelledly", "aria-current", "aria-expanded", "aria-controls", "aria-hidden", "aria-describedby", "tabindex", "aria-modal", "data-bs-toggle", "data-bs-target", "data-bs-dismiss", "data-bs-slide", "data-bs-slide-to", "data-bs-parent", "data-bs-config", "data-bs-content", "data-bs-spy"]
#      - name: snippet
#        tags: ["a"]
#        attributes: ["data-url", "data-ajax-modal", "data-prev-url"]
#        custom_attributes:
#          - tags: ["a"]
#            attributes: ["data-url", "data-ajax-modal", "data-prev-url"]
#
#    fields:
#      - name: product_translation.description
#        sets: ["basic", "media", "HTML5"]
#      - name: app_cms_block.template
#        sets: ["basic", "media", "tidy", "HTML5"]
#      - name: snippet.value
#        sets: ["basic", "media", "bootstrap", "snippet", "HTML5"]
#
#  logger:
#    enforce_throw_exception: '%env(bool:default:defaults_bool_false:LOGGER_ENFORCE_THROW_EXCEPTION)%'
#    file_rotation_count: 14
#    exclude_exception:
#      - League\OAuth2\Server\Exception\OAuthServerException
#      - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
#      - Shopware\Core\Framework\Routing\Exception\LanguageNotFoundException
#    exclude_events:
#      - user.recovery.request
#      - customer.recovery.request
#    error_code_log_levels:
#      CHECKOUT__CART_HASH_MISMATCH: notice
#      CHECKOUT__INSUFFICIENT_PERMISSION: notice
#      CHECKOUT__TAX_ID_NOT_FOUND: notice
#      CHECKOUT__CUSTOMER_NOT_FOUND: notice
#      CHECKOUT__CUSTOMERS_NOT_FOUND: notice
#      CHECKOUT__CUSTOMER_NOT_LOGGED_IN: notice
#      CHECKOUT__CUSTOMER_AUTH_BAD_CREDENTIALS: notice
#      CHECKOUT__CUSTOMER_IS_ALREADY_CONFIRMED: notice
#      CHECKOUT__CUSTOMER_NOT_FOUND_BY_HASH: notice
#      CHECKOUT__CUSTOMER_NOT_FOUND_BY_ID: notice
#      CHECKOUT__CUSTOMER_RECOVERY_HASH_EXPIRED: notice
#      CHECKOUT__WISHLIST_NOT_FOUND: notice
#      CHECKOUT__DUPLICATE_WISHLIST_PRODUCT: notice
#      CHECKOUT__LEGACY_PASSWORD_ENCODER_NOT_FOUND: notice
#      CHECKOUT__WISHLIST_PRODUCT_NOT_FOUND: notice
#      CHECKOUT__CUSTOMER_AUTH_THROTTLED: notice
#      CHECKOUT__CUSTOMER_OPTIN_NOT_COMPLETED: notice
#      CHECKOUT__LINE_ITEM_DOWNLOAD_FILE_NOT_FOUND: notice
#      CHECKOUT__ORDER_CUSTOMER_NOT_LOGGED_IN: notice
#      CHECKOUT__ASYNC_PAYMENT_FINALIZE_INTERRUPTED: notice
#      CHECKOUT__ASYNC_PAYMENT_PROCESS_INTERRUPTED: notice
#      CHECKOUT__CAPTURE_PREPARED_PAYMENT_ERROR: notice
#      CHECKOUT__CUSTOMER_CANCELED_EXTERNAL_PAYMENT: notice
#      CHECKOUT__SYNC_PAYMENT_PROCESS_INTERRUPTED: notice
#      CHECKOUT__RECURRING_PROCESS_INTERRUPTED: notice
#      CHECKOUT__REFUND_PROCESS_INTERRUPTED: notice
#      CHECKOUT__PAYMENT_TOKEN_EXPIRED: notice
#      CHECKOUT__PAYMENT_TOKEN_INVALIDATED: notice
#      CHECKOUT__CART_LINE_ITEM_NOT_STACKABLE: notice
#      CHECKOUT__CART_LINE_ITEM_TYPE_NOT_UPDATABLE: notice
#      CHECKOUT__INVALID_PAYMENT_TOKEN: notice
#      DOCUMENT__INVALID_GENERATOR_TYPE: notice
#      DOCUMENT__INVALID_RENDERER_TYPE: notice
#      DOCUMENT__NUMBER_ALREADY_EXISTS: notice
#      DOCUMENT__DOCUMENT_NOT_FOUND: notice
#      DOCUMENT__GENERATION_ERROR: notice
#      DOCUMENT__ORDER_NOT_FOUND: notice
#      CHECKOUT__PROMOTION__NOT_FOUND: notice
#      CHECKOUT__PROMOTION_DISCOUNT_NOT_FOUND: notice
#      CONTENT__DELETION_DEFAULT_CMS_PAGE: notice
#      CONTENT__DELETION_OVERALL_DEFAULT_CMS_PAGE: notice
#      CONTENT__INVALID_FIELD_CONFIG_SOURCE: notice
#      CONTENT__MEDIA_INVALID_CONTENT_LENGTH: notice
#      CONTENT__MEDIA_INVALID_URL: notice
#      CONTENT__MEDIA_ILLEGAL_URL: notice
#      CONTENT__MEDIA_DISABLE_URL_UPLOAD_FEATURE: notice
#      CONTENT__MEDIA_CANNOT_OPEN_SOURCE_STREAM_TO_READ: notice
#      CONTENT__MEDIA_CANNOT_OPEN_SOURCE_STREAM_TO_WRITE: notice
#      CONTENT__MEDIA_FILE_SIZE_LIMIT_EXCEEDED: notice
#      CONTENT__MEDIA_MISSING_FILE_EXTENSION: notice
#      CONTENT__MEDIA_MISSING_URL_PARAMETER: notice
#      CONTENT__MEDIA_ILLEGAL_FILE_NAME: notice
#      CONTENT__MEDIA_EMPTY_FILE: notice
#      CONTENT__MEDIA_INVALID_FILE: notice
#      CONTENT__MEDIA_EMPTY_FILE_NAME: notice
#      CONTENT__MEDIA_FOLDER_NOT_FOUND: notice
#      CONTENT__MEDIA_FOLDER_NAME_NOT_FOUND: notice
#      CONTENT__MEDIA_FILE_TYPE_NOT_SUPPORTED: notice
#      CONTENT__MEDIA_EMPTY_ID: notice
#      CONTENT__MEDIA_FILE_NOT_SUPPORTED_FOR_THUMBNAIL: notice
#      CONTENT__MEDIA_STRATEGY_NOT_FOUND: notice
#      CONTENT__MEDIA_DUPLICATED_FILE_NAME: notice
#      CONTENT__MEDIA_NOT_FOUND: notice
#      CONTENT__MEDIA_MISSING_FILE: notice
#      CONTENT__NEWSLETTER_RECIPIENT_THROTTLED: notice
#      CONTENT__PRODUCT_EXPORT_EMPTY: notice
#      ELASTICSEARCH_PRODUCT__CANNOT_CHANGE_CUSTOM_FIELD_TYPE: notice
#      FRAMEWORK__APP_NOT_COMPATIBLE: notice
#      FRAMEWORK__APP_INTEGRATION_NOT_FOUND: notice
#      FRAMEWORK__API_INVALID_ACCESS_KEY: notice
#      FRAMEWORK__API_SALES_CHANNEL_MAINTENANCE_MODE: notice
#      FRAMEWORK__CANNOT_CREATE_NEW_VERSION: notice
#      FRAMEWORK__EXTENSION_THEME_STILL_IN_USE: notice
#      FRAMEWORK__INVALID_SALES_CHANNEL_MAPPING: notice
#      FRAMEWORK__LANGUAGE_NOT_FOUND: notice
#      FRAMEWORK__SYNC_ACTION_PROCESS_INTERRUPTED: notice
#      FRAMEWORK__WRITE_TYPE_INTEND_ERROR: notice
#      FRAMEWORK__MISSING_REQUEST_PARAMETER: notice
#      FRAMEWORK__INVALID_REQUEST_PARAMETER: notice
#      FRAMEWORK__INVALID_TEMPLATE_SYNTAX: notice
#      FRAMEWORK__RATE_LIMIT_EXCEEDED: notice
#      FRAMEWORK__SALES_CHANNEL_NOT_FOUND: notice
#      PRODUCT__CATEGORY_NOT_FOUND: notice
#      PRODUCT_CONFIGURATION_OPTION_EXISTS_ALREADY: notice
#      PRODUCT_EXPORT__RENDER_FOOTER_EXCEPTION: notice
#      PRODUCT_EXPORT__RENDER_HEADER_EXCEPTION: notice
#      PRODUCT_EXPORT__RENDER_PRODUCT_EXCEPTION: notice
#      PRODUCT_SORTING_NOT_FOUND: notice
#      PROMOTION__INDIVIDUAL_CODES_PATTERN_ALREADY_IN_USE: notice
#      PROMOTION__INDIVIDUAL_CODES_PATTERN_INSUFFICIENTLY_COMPLEX: notice
#      SYSTEM__SCOPE_NOT_FOUND: notice
#      SYSTEM__STATE_MACHINE_INVALID_ENTITY_ID: notice
#      SYSTEM__SALES_CHANNEL_DOES_NOT_EXISTS: notice
#      SYSTEM__LANGUAGE_INVALID_EXCEPTION: notice
#      SYSTEM__COUNTRY_DOES_NOT_EXISTS_EXCEPTION: notice
#      SYSTEM__CURRENCY_DOES_NOT_EXISTS_EXCEPTION: notice
#      SYSTEM__COUNTRY_STATE_DOES_NOT_EXISTS_EXCEPTION: notice
#      SYSTEM__SALES_CHANNEL_LANGUAGE_NOT_AVAILABLE_EXCEPTION: notice
#      SYSTEM__NO_CONTEXT_DATA_EXCEPTION: notice
#
#  cache:
#    redis_prefix: '%env(REDIS_PREFIX)%'
#    tagging:
#      each_snippet: true
#      each_config: true
#      each_theme_config: true
#    invalidation:
#      delay: 0
#      delay_options:
#        storage: mysql
#      http_cache: ['logged-in', 'cart-filled']
#      product_listing_route: []
#      product_detail_route: []
#      product_review_route: []
#      product_search_route: []
#      product_suggest_route: []
#      product_cross_selling_route: []
#      payment_method_route: []
#      shipping_method_route: []
#      navigation_route: []
#      category_route: []
#      landing_page_route: []
#      language_route: []
#      currency_route: []
#      country_route: []
#      country_state_route: []
#      salutation_route: []
#      sitemap_route: []
#
  twig:
    allowed_php_functions: []
#
#  dompdf:
#    options:
#      isRemoteEnabled: true
#
#  stock:
#    enable_stock_management: true
#
#  usage_data:
#    gateway:
#      dispatch_enabled: true
#      base_uri: 'https://data.shopware.io'
#      batch_size: 50
#
#  feature_toggle:
#    enable: true
#
#  search:
#    term_max_length: 300
#    # special chars that will not be removed on tokenizing
#    preserved_chars: ['-', '_', '+', '.', '@']
#
#  staging:
#    mailing:
#      disable_delivery: true
#    storefront:
#      show_banner: true
#    administration:
#      show_banner: true
#    sales_channel:
#      domain_rewrite: []
#    elasticsearch:
#      check_for_existence: true
#
#  system_config:
#    default: []
#
#  messenger:
#    routing_overwrite:
#
#  product_stream:
#    indexing: true
